#!/usr/bin/env julia
using PyPlot
using OhMyJulia
using ProgressMeter

sta_dir, sam_dir = rel"../statistic", rel"../processed"

for t in (:cfdna, :gdna)
    x, y, m = ASCIIString[], Vector{Int}[], Int[]

    @showprogress 1 "loading $t..." for i in readdir(sam_dir)
        try
            r = readdlm("$sam_dir/$i/$(i)_$(t)_mark.txt")[:, 6]
            push!(x, i)
            push!(y, r)
            push!(m, median(r))
        catch e
            println(STDERR, i, e)
        end
    end

    const sorting_methods = Dict(
        :name   => i -> parse(Int, match(r"(\d+)$", x[i])[1]),
        :median => i -> -m[i]
    )

    for sorting in (:name, :median)
        p = sortperm(collect(1:length(x)), by=sorting_methods[sorting])

        figure(figsize=(16, 9), dpi=120)
        boxplot(y[p], showfliers=false)
        xticks(collect(1:length(x)), x[p], rotation=90)
        ylabel("Coverage in Each Targeted Exon")
        savefig("$sta_dir/depth_distribution_$(t)_sorted_by_$sorting.png")
        clf()
    end

    open("$sta_dir/depth_median_$t.txt", "w") do f
        @printf(f, "%-8s %6s\n", "#Sample", "Median")
        for i in 1:length(m)
            @printf(f, "%-8s %6s\n", x[i], ceil(Int, m[i]))
        end
        @printf(f, "%-8s %6s\n", "#All", ceil(Int, median(m)))
    end
end
